# cloudbuild.yaml
# Despliega la Cloud Function Gen2 con gcloud cuando hay push a main.
# Puedes sobrescribir estas sustituciones desde el Trigger.

substitutions:
  _PROJECT_ID: silver-argon-461815-d7
  _REGION: us-central1
  _FUNCTION_NAME: procesador-facturas         # usa este nombre (coincide con tus logs)
  _ENTRY_POINT: procesar_facturas
  _INPUT_BUCKET: facturas-entrada-xyz
  _PROCESSED_BUCKET: facturas-procesadas-xyz
  _SPREADSHEET_ID: 1u4llynfMnPZUqqNskuCzkQhC1XwI5n0_dL8ozLhvSl4
  _SAMS_PROCESSOR_ID: 46bf76b2d9ec6795
  _SAMS_PROCESSOR_VERSION_ID: 5e846c053f59be04
  _CITY_PROCESSOR_ID: f6ea58d6735bbf51
  _CITY_PROCESSOR_VERSION_ID: pretrained-foundation-model-v1.5-2025-05-05
  _DOCAI_LOCATION: us

steps:
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -lc
      - |
        set -euo pipefail
        echo "Deploying Cloud Function Gen2 ${_FUNCTION_NAME} in ${_PROJECT_ID}/${_REGION}..."
        gcloud functions deploy "${_FUNCTION_NAME}" \
          --project "${_PROJECT_ID}" \
          --gen2 \
          --runtime python311 \
          --region "${_REGION}" \
          --entry-point "${_ENTRY_POINT}" \
          --trigger-bucket "${_INPUT_BUCKET}" \
          --set-env-vars \
PROJECT_ID="${_PROJECT_ID}",DOCAI_LOCATION="${_DOCAI_LOCATION}",INPUT_BUCKET="${_INPUT_BUCKET}",PROCESSED_BUCKET="${_PROCESSED_BUCKET}",SPREADSHEET_ID="${_SPREADSHEET_ID}",SAMS_PROCESSOR_ID="${_SAMS_PROCESSOR_ID}",SAMS_PROCESSOR_VERSION_ID="${_SAMS_PROCESSOR_VERSION_ID}",CITY_PROCESSOR_ID="${_CITY_PROCESSOR_ID}",CITY_PROCESSOR_VERSION_ID="${_CITY_PROCESSOR_VERSION_ID}"

options:
  logging: CLOUD_LOGGING_ONLY

timeout: "1200s"
